### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by f0rmat1k** [rpominov/svgo-loader#21] opened 2017-11-12 15:54 UTC
Hello. Trouble with 2.0.0; 1.2.1 is ok.

Webpack 3.8.1
Config:
```js
{
                        loader: 'svgo-loader',
                        options: {
                            plugins: [
                                {removeTitle: true},
                                {convertColors: {shorthex: false}},
                                {convertPathData: false},
                                {removeUselessDefs: false}
                            ]
                        }
                    }
```

stacktrace:
```bash
       ERROR in ./src/components/rs-logo/rs-logo.svg
        Module build failed: TypeError: callback is not a function
            at optimizeOnceCallback (/Users/f0rmat1k/projects/tststub/node_modules/svgo/lib/svgo.js:44:17)
            at /Users/f0rmat1k/projects/tststub/node_modules/svgo/lib/svgo.js:65:9
            at SAXParser.sax.onend (/Users/f0rmat1k/projects/tststub/node_modules/svgo/lib/svgo/svg2js.js:156:13)
            at emit (/Users/f0rmat1k/projects/tststub/node_modules/sax/lib/sax.js:624:35)
            at end (/Users/f0rmat1k/projects/tststub/node_modules/sax/lib/sax.js:667:5)
            at SAXParser.write (/Users/f0rmat1k/projects/tststub/node_modules/sax/lib/sax.js:975:14)
            at SAXParser.close (/Users/f0rmat1k/projects/tststub/node_modules/sax/lib/sax.js:157:38)
            at module.exports (/Users/f0rmat1k/projects/tststub/node_modules/svgo/lib/svgo/svg2js.js:169:28)
            at module.exports.SVGO._optimizeOnce (/Users/f0rmat1k/projects/tststub/node_modules/svgo/lib/svgo.js:56:5)
            at module.exports.SVGO.optimize (/Users/f0rmat1k/projects/tststub/node_modules/svgo/lib/svgo.js:49:11)
            at Object.module.exports (/Users/f0rmat1k/projects/tststub/node_modules/svgo-loader/index.js:27:8)
         @ ./node_modules/css-loader!./node_modules/postcss-loader/lib?{"plugins":[null,null]}!./src/components/rs-logo/rs-logo.css 6:131-155
```

**Comment by rpominov** [comment] 2017-11-12 16:01
What version of `svgo` you have installed? If it below `1.0.0`, you need to update to `1.0.0` or higher.

Btw, I wonder how you get to that state. You've updated `svg-loader` right? Did npm warn you that after the update you have a missing peer dependency? I think it should warn, we have `^1.0.0` specified in our `package.json`: https://github.com/rpominov/svgo-loader/blob/3864ea3104bf53b8037016013e3cb0951439da1c/package.json#L28

**Comment by f0rmat1k** [comment] 2017-11-12 16:09
@rpominov I don't have installed svgo. I've just look, svgo-loader uses `peerDependencies`. Why not `dependencies`?

**Comment by rpominov** [comment] 2017-11-12 16:15
The idea is to let users install any version of `svgo` that they want.

**Comment by f0rmat1k** [comment] 2017-11-12 16:18
It's strange, but i'm getting 0.7.2 after clear `npm install`.
```json
{
  "_from": "svgo@^0.7.0",
  "_id": "svgo@0.7.2",
  "_inBundle": false,
  "_integrity": "sha1-n1dyQTlSE1xv779Ar+ak+qiLS7U=",
  "_location": "/svgo",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "svgo@^0.7.0",
    "name": "svgo",
    "escapedName": "svgo",
    "rawSpec": "^0.7.0",
    "saveSpec": null,
    "fetchSpec": "^0.7.0"
  },
  "_requiredBy": [
    "/postcss-svgo"
  ],
```

**Comment by f0rmat1k** [comment] 2017-11-12 16:20
btw, the problem is in our generator based on yeoman. It clearly installs all dependencies and runs test in drone with node6. I'm having this issue too locally with node 8.

**Comment by rpominov** [comment] 2017-11-12 16:22
Yeah, strange. I don't understand why this's happening. Also reported here #20

**Comment by rpominov** [comment] 2017-11-13 11:23
Closing as a duplicate of #20

**Closed as completed by rpominov** 2017-11-13 11:23 UTC
