### ISSUE TITLE
TypeError: loadConfig is not a function

### ISSUE THREAD

**Issue by michaeldietiker** [rpominov/svgo-loader#61] opened 2024-05-08 06:36 UTC
If I upgrade svgo from 3.2.0 to 3.3.0 I get the following error:

Module build failed (from ./node_modules/svgo-loader/index.js):
TypeError: loadConfig is not a function
    at Object.loader (/var/www/html/node_modules/svgo-loader/index.js:9:20)
    at module.exports (/var/www/html/node_modules/svgo-loader/index.js:17:10)
 @ ./src/icons/ sync nonrecursive \.svg$/ ./chevron-16.svg
 @ ./src/scripts/main.js 3:12-58

**Comment by rpominov** [comment] 2024-05-08 07:10
From what you said it sounds like [`loadConfig`](https://github.com/svg/svgo?tab=readme-ov-file#loadconfig) was removed from `svgo` in 3.3.0, which would be strange since it's not a major release and the function still listed in the docs.

You might want to also try using `loadConfig` from `svgo` directly without `svgo-loader` to see if it works, and open issue at `svgo`.

Not sure I'll have time to dig into this myself soon, so a PR with a fix — if one needed in this repo — would be appreciated!

**Comment by tarjep** [comment] 2024-05-08 14:32
We are also suddenly getting the same error without touching any of our dependencies. Any temp workarounds?
We are on the latest release of svgo-loader 4.0.0

**Comment by ximex** [comment] 2024-05-08 14:47
temporary workaround in `package.json`:
```json
"overrides": {
	"svgo-loader@^4.0.0": {
		"svgo": "3.2.0"
	}
}
```

**Comment by rpominov** [comment] 2024-05-08 15:18
Looks like it's already being worked on in svgo: https://github.com/svg/svgo/pull/1984

Closing this issue since the problem is in another package.

**Closed as completed by rpominov** 2024-05-08 15:18 UTC

**Comment by SethFalco** [comment] 2024-05-08 23:40
I apologize for the headache!

Indeed, this was a mistake while migrating from CJS to ESM, and generating the CJS bundle. The `loadConfig` function wasn't exported, and we didn't have a test for that. I've written a formal notice for what happened in the release notes for v3.3.1:

https://github.com/svg/svgo/releases/tag/v3.3.1

I'll put safeguards in place to reduce the risk of that happening again in future. Meanwhile, feel free to open an issue in [svg/svgo](https://github.com/svg/svgo) if you encounter any other issues.
